server: {}
#  cert: SELF-SIGNED-CERT.crt
#  key: SELF-SIGNED-CERT.key

connections: {}
#  mqtt:
#    url: mqtt://localhost

providers: {}
#  androidtv:
#    host: "ANDROID-TV-IP"
#    pair_port: 6467
#    port: 6466
#    cert: SELF-SIGNED-CERT.crt
#    key: SELF-SIGNED-CERT.key
#    service_name: SmartHome
#    model: SmartHome
#    manufacturer: iTimmer
#    secret: PAIRED-SECRET
#  denon:
#    host: "DENON-IP"
#  hue:
#    host: "https://HUE-BRIDGE-IP"
#    key: HUE-API-KEY
#  hue_genesis:
#    client_id: OFFICIAL_HUE_APP_CLIENT_ID
#    client_secret: OFFICIAL_HUE_APP_CLIENT_SECRET
#  ista:
#    username: USERNAME
#    password: PASSWORD
#  openmeteo:
#    latitude: LATITUDE
#    longitude: LONGITUDE
#  philipstv:
#    url: "https://PHILIPS-TV-IP:1926/6"
#    username: PHILIPS-TV-USERNAME
#    password: PHILIPS-TV-PASSWORD
#  slide:
#    email: SLIDE-EMAIL
#    password: SLIDE-PASSWORD
#  spotify:
#    client_id: SPOTIFY-CLIENT-ID
#    client_secret: SPOTIFY-CLIENT-SECRET
#    code: SPOTIFY-CODE
#    refresh_token: SPOTIFY-REFRESH-TOKEN
#  suncalc:
#    latitude: LATITUDE
#    longitude: LONGITUDE
#  teslamate: {}
#  unifi:
#    url: http://localhost:8443
#    username: USERNAME
#    password: PASSWORD
#  zwave:
#    port: /dev/ttyACM0
#    keys:
#      s2_unauthenticated: ZWAVE-S2-UNAUTHENTICATED-KEY-HEX
#      s2_authenticated: ZWAVE-S2-AUTHENTICATED-KEY-HEX
#      s2_access_control: ZWAVE-S2-ACCESS-CONTROL-KEY-HEX
#      s0: ZWAVE-S0-KEY-HEX

history:
#  logger:
#    type: influxdb
#    url: "http://INFLUXDB-IP:8086"
#    token: INFLUXDB-TOKEN
#    organisation: Smarthome
#    bucket: Smarthome
  track: []
    # Example to track all temperature sensors
    #- service_type: temperatureSensor
    #  property_type: temperature

scenes: {}
#  example1:
#    name: Hue Off
#    id: provider:home
#    values:
#      "hue:GUID": { on: false }

rules: []
#  - script: rule.example.js
#    aliases:
#      sensor: "uuid:HUE-SENSOR-DEVICE-GUID"
#      lights: "hue:LIGHTS-UUID"
#    config:
#      keep_on: 5 #minutes
#      daylight_level: 16000
#      dark_level: 20000
